# Constants
# Image settings
IMAGE_WIDTH = 770
IMAGE_HEIGHT = 420
MARGIN = 100  # 50px on each side
DRAW_WIDTH = IMAGE_WIDTH - MARGIN
DRAW_HEIGHT = IMAGE_HEIGHT - MARGIN

# Geographical transformations
VERT_STRETCH = 1.08
XAX_SHIFT = 0.08
YAX_SHIFT = 0.05
